### ISSUE TITLE
include dependencies in the src

### ISSUE THREAD

**Issue by thanhdowisc** [PivotalRD/libhdfs3#6]
Currently, the assumption is that dependencies such as protobuf, libhdfs, and kerberos are readily available on the host OS. We should put these library in the src (similar to gtest and gmock) and build them as part of the make process.

In the long term, it is better to get rid of as many dependencies as possible. For instance, can we just use c++ STL instead of libxml2?

**Comment by thanhdowisc** [comment]
Hi Zhanwei. 

I would like to get rid of as many dependencies as possible and whenever possible use c++ STL instead. It seems that we cannot replace Protobuf and Kerberos. But what about libgasl? Also, as Colin mentioned in JIRA, we can replace libuuid with our own code as well.

Do we really have to depend on Boost? 

Could you give some comment on this topic? Could you list some dependencies that we can definitely get rid of?

Thanks,
Thanh

**Comment by wangzw** [comment]
Hi Thanh

All dependencies are listed in [this page](https://github.com/PivotalRD/libhdfs3/wiki/Requirements-&-Dependencies)

libuuid can definitely be removed. But others are not easy to get rid of. 

I'm very happy if we can remove as many dependencies as possible, but I also do not want to reinvent the wheel. For long term target, we only use C++ STL, but we have to face the following situation.

1) Support old compiler. 
For example, the default GCC of Red hat 6 is GCC 4.4.7 and many people use it in production. We can remove Boost for latest GCC but we have to depend on Boost with GCC 4.4.7.

2) Including dependencies in src may introduce trouble in some case. 
In Pivotal, all dependencies must be managed and fully tested in the production. all dependencies must be compiled with specified compiler with specified flag and using specified version. If we include dependencies in src, we have to face the dilemma of choosing version. gmock and gtest are only used for test so that we can include them in src.

The good news is that Boost is not required if you build libhdfs3 with GCC 4.8. I'm optimism and let's remove libuuid first, and try others later.

**Comment by thanhdowisc** [comment]
Zhanwei,

You have raised a good point on dependencies in production. I couldn't agree with you more.

However, in the windows branch, in order to support continuous integration, I still need to include the dependencies in the source and compile them together with libhdfs3. The reason is that it is not easy to install dependencies in windows because there is now such command like "sudo apt-install install libprotobuf".

**Comment by wangzw** [comment]
I see, how about we create a new repository named ```libhdfs3-dependencies``` and download the dependencies from this repository when we run CI on windows?

**Comment by thanhdowisc** [comment]
+1.

I will do that on the windows branch, which I will start on it shortly.

**Comment by wangzw** [comment]
[libhdfs3-dependencies](https://github.com/PivotalRD/libhdfs3-dependencies) repository is created.
